import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import myImage from '@/app/assets/homepage.png';
import { Suspense } from 'react';
import Loading from './loading';
import { CustomComponent } from './components';
import Link from 'next/link';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'yanyunchangfeng',
  description: 'Generated by yanyunchangfeng'
};
// app 目录必须包含根布局，也就是 app/layout.tsx 这个文件是必需的。
// 根布局必须包含 html 和 body标签，其他布局不能包含这些标签。如果你要更改这些标签，不推荐直接修改，参考《Metadata 篇》。
// 你可以使用路由组创建多个根布局。
// 默认根布局是服务端组件，且不能设置为客户端组件。

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{
          backgroundImage: `url(${myImage.src})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat'
        }}
      >
        <div className="p-5">
          <nav className="flex items-center justify-center gap-10 text-blue-600">
            <Link href="/blog">blog</Link>
            <Link href="/dashboard">dashboard</Link>
          </nav>
          {/* 在布局中使用 Suspense，组件在导航的时候不会发生改变。而在模板中使用 Suspense，组件在导航的时候每次都会触发 Loading 效果。 */}
          <Suspense fallback={<Loading />}>
            <CustomComponent title="layout" />
          </Suspense>
          {children}
        </div>
      </body>
    </html>
  );
}

// 也就是说 layout 会包裹 template，template 又会包裹 page。
